sudo: 'required'

services:
  - 'docker'

before_install:
  - chmod +x './.travis/main.sh'
  - './.travis/main.sh'

language: java
env:
  - spring_profiles_active=local
cache:
  npm: true
  directories:
    - $HOME/.m2
deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker build -f Dockerfile.mico-core -t ustmico/mico-core:latest .
  on:
    branch: master
